spring:
  devtools:
    add-properties: false
  application:
    name: '@project.artifactId@'
  profiles:
    active: '${PROJECT_PROFILE:@spring.profiles.active@}'
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    default-property-inclusion: NON_NULL
    locale: pt-BR
    time-zone: America/Sao_Paulo
  datasource:
    driverClassName: 'org.postgresql.Driver'
    url: '${DB_URL:jdbc:postgresql://localhost:5432/blog}'
    username: '${DB_USER:@db.user@}'
    password: '${DB_PASSWORD:@db.password@}'
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 3000
      idleTimeout: 60000
      maxLifetime: 180000
      maximum-pool-size: 50
      minimum-idle: 1
  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    generate-ddl: false
    open-in-view: true
    show_sql: '${HOW_SQL:@db.show_sql@}'
    hibernate:
        ddl-auto: '@db.ddl-auto@'
  flyway:
    user: '${DB_USER:@db.user@}'
    password: '${DB_PASSWORD:@db.password@}'
    schemas: '${DB_SCHEMAS:@db.schema@}'
    enabled: '${DB_FLYWAY:@db.flyway.enabled@}'
  security:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true
  packagesToScan: br.com.blog.controller.impl
  packages-to-exclude: br.com.blog.commons.controller, br.com.blog.entities
  show-atuator: true
  auto-tag-classes: false
# JWT
jwt:
  secret: _@POE&L3tF?65O9j4z&L5!nU2B!eT65_
  expiration: 86400 # token com durao de 1 dias
debug: '${DEBUG:@debug.properties@}'
trace: '${TRACE:@trace.properties@}'
server:
  compression:
    enabled: true
    min-response-size: 1
  port: '${SERVER_PORT:@port@}'
  undertow:
    accesslog:
      dir: logs
      enabled: false
      pattern: '%t %a "%r" %s (%D ms)'
logging:
  level:
    org:
      springframework:
        test: ERROR
      hibernate: warn
      xnio: warn
      jboss: warn
    io:
      undertow: warn
    com:
      zaxxer:
        hikari:
          HikariDataSource: warn
# Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'