version: "3.9"
services:
  pgsql-blog:
    image: postgres:13.3-alpine
    container_name: pgsql-blog
    restart: on-failure
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=1q2w3e
    ports:
      - "5432:5432"
    volumes:
      - "pgsqlconfBlog:/etc/postgresql"
      - "pgsqldataBlog:/var/lib/postgresql/data"
      - "pgsqldblogsBlog:/var/log"
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-4
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=112358
    ports:
      - "5050:80"
    volumes:
      - "pgadmin4sessiondata:/var/lib/pgadmin"
      - "pgadmin4conf:/pgadmin4/config_local.py"
      - "pgadmin4serverdefinitions:/pgadmin4/servers.json"
    depends_on:
      - pgsql-blog

volumes:
  pgsqlconfBlog:
  pgsqldataBlog:
  pgsqldblogsBlog:
  pgadmin4sessiondata:
  pgadmin4conf:
  pgadmin4serverdefinitions:

networks:
  default:
    external: true
    name: net-blog